# Generated by Django 5.2.10 on 2026-02-10 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0006_alter_aiconfiguration_active_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='user_rate_limit_per_hour',
            field=models.PositiveIntegerField(default=9999, help_text='الحد الأقصى لطلبات AI لكل مستخدم في الساعة', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)], verbose_name='حد الطلبات/ساعة للمستخدم'),
        ),
    ]
